# test_tools.py
from tools import init_db, get_website_title, add_lead_to_db


def run_tests():
    print("--- [Phase 2] Starting Tool Verification ---")

    # Test 1: Initialize the database
    print("\n[Test 1: Initializing Database]")
    init_db()

    # Test 2: Scrape a valid website title
    print("\n[Test 2: Scraping a valid website]")
    domain_to_test = "chelseaai.co.uk"
    title = get_website_title(domain_to_test)
    print(f"Scraped title for '{domain_to_test}': {title}")
    assert "Chelsea AI" in title  # Check for a keyword in the title

    # Test 3: Handle a non-existent domain
    print("\n[Test 3: Scraping a non-existent domain]")
    bad_domain = "thissitedoesnotexist12345.com"
    error_message = get_website_title(bad_domain)
    print(f"Response for '{bad_domain}': {error_message}")
    assert "Could not scrape website" in error_message

    # Test 4: Add a dummy lead to the database
    print("\n[Test 4: Adding Dummy Lead to DB]")
    dummy_lead = {
        "name": "John Doe (Test)",
        "email": "john.doe@testcorp.com",
        "message": "This is a test message for the database.",
        "company_title": "Test Corporation Inc.",
        "classification": "B-Lead",
        "score": "80",
        "drafted_reply": "This is a test reply generated by the system.",
    }
    add_lead_to_db(dummy_lead)

    print("\n--- [Phase 2] Tool Verification Complete ---")


if __name__ == "__main__":
    run_tests()
